import fs from 'node:fs';
import assert from 'node:assert/strict';

const ROOT='factory-native';
const scenePath=`${ROOT}/assets/ReferenceGame01.scene`;
const sceneMetaPath=`${scenePath}.meta`;
const bootstrapPath=`${ROOT}/assets/scripts/cocos/PlayableBootstrap.ts`;
const bootstrapMetaPath=`${bootstrapPath}.meta`;
for(const p of [scenePath,sceneMetaPath,bootstrapPath,bootstrapMetaPath])assert.ok(fs.existsSync(p),`missing playable Cocos asset ${p}`);
const scene=JSON.parse(fs.readFileSync(scenePath,'utf8'));
assert.equal(scene[0].__type__,'cc.SceneAsset');
assert.equal(scene[1].__type__,'cc.Scene');
assert.equal(scene[2]._name,'Bootstrap');
assert.equal(scene[3].__type__,'6b3e1+QT3RLUYyCT5xtKajx');
assert.equal(scene[3].node.__id__,2);
const sceneMeta=JSON.parse(fs.readFileSync(sceneMetaPath,'utf8'));
assert.equal(sceneMeta.importer,'scene');
const bootstrapMeta=JSON.parse(fs.readFileSync(bootstrapMetaPath,'utf8'));
assert.equal(bootstrapMeta.importer,'typescript');
assert.equal(bootstrapMeta.uuid,'6b3e1f90-4f74-4b51-8c82-4f9c6d29a8f1');
const bootstrap=fs.readFileSync(bootstrapPath,'utf8');
for(const phrase of ['addComponent(Canvas)','addComponent(LayeredSceneRenderer)','addComponent(ReferenceGameController)','addComponent(ResultCardController)','addComponent(ReferenceGameFlow)','Button.EventType.CLICK','BEAT YOUR BEST','await flow.start()'])assert.ok(bootstrap.includes(phrase),`playable bootstrap missing ${phrase}`);
const flow=fs.readFileSync(`${ROOT}/assets/scripts/cocos/ReferenceGameFlow.ts`,'utf8');
for(const phrase of ['bindController()','resetSession()','preserveRoundCounters','markReplay()','loadRound(this.session.roundIndex,true)'])assert.ok(flow.includes(phrase),`meta flow missing ${phrase}`);
const controller=fs.readFileSync(`${ROOT}/assets/scripts/cocos/ReferenceGameController.ts`,'utf8');
for(const phrase of ['resetSession()','preserveRoundCounters','if(!preserveRoundCounters)'])assert.ok(controller.includes(phrase),`controller reset/replay contract missing ${phrase}`);
const result=fs.readFileSync(`${ROOT}/assets/scripts/cocos/ResultCardController.ts`,'utf8');
for(const phrase of ['PERCEPTION SCORE','BEST ','BEAT YOUR BEST','continueButton.interactable'])assert.ok(result.includes(phrase),`result card lacks continuation value ${phrase}`);
console.log('COCOS_PLAYABLE_SCENE_CONTRACT_PASS');
